name: Supabase Keep-Alive

on:
  schedule:
    # Runs at 15:00 UTC (8:00 AM Pacific Time) every Monday and Friday
    - cron: '0 15 * * 1,5'
  workflow_dispatch: # Allows manual trigger

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install @supabase/supabase-js
        
      - name: Run keep-alive script
        run: npx tsx scripts/keep-alive.ts
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }} 